var dataTags = {
	cr: [
		{"key": "habitat", "value": 328},
		{"key": "population", "value": 238},
		{"key": "area", "value": 218},
		{"key": "hunting", "value": 196},
		{"key": "forest", "value": 180},
		{"key": "loss", "value": 125},
		{"key": "range", "value": 124},
		{"key": "decline", "value": 99},
		{"key": "human", "value": 94},
		{"key": "mink", "value": 92},
		{"key": "per", "value": 84},
		{"key": "island", "value": 82},
		{"key": "protected", "value": 82},
		{"key": "logging", "value": 80},
		{"key": "threatened", "value": 79},
		{"key": "small", "value": 77},
		{"key": "local", "value": 75},
		{"key": "animal", "value": 69},
		{"key": "year", "value": 69},
		{"key": "park", "value": 63},
		{"key": "within", "value": 63},
		{"key": "impact", "value": 62},
		{"key": "wild", "value": 58},
		{"key": "known", "value": 52},
		{"key": "deforestation", "value": 51},
		{"key": "factor", "value": 51},
		{"key": "hunted", "value": 51},
		{"key": "use", "value": 51},
		{"key": "dog", "value": 49},
		{"key": "likely", "value": 48},
		{"key": "large", "value": 46},
		{"key": "mortality", "value": 45},
		{"key": "people", "value": 45},
		{"key": "region", "value": 45},
		{"key": "fire", "value": 43},
		{"key": "food", "value": 43},
		{"key": "pressure", "value": 43},
		{"key": "agriculture", "value": 42},
		{"key": "change", "value": 42},
		{"key": "individual", "value": 42},
		{"key": "well", "value": 42},
		{"key": "predation", "value": 41},
		{"key": "reserve", "value": 41},
		{"key": "two", "value": 41},
		{"key": "activities", "value": 40},
		{"key": "american", "value": 40},
		{"key": "conversion", "value": 40},
		{"key": "effect", "value": 40},
		{"key": "gorilla", "value": 40},
		{"key": "land", "value": 40},
		{"key": "main", "value": 39},
		{"key": "rate", "value": 39},
		{"key": "cat", "value": 38},
		{"key": "level", "value": 38},
		{"key": "number", "value": 38},
		{"key": "remaining", "value": 38},
		{"key": "pet", "value": 37},
		{"key": "size", "value": 37},
		{"key": "will", "value": 37},
		{"key": "agricultural", "value": 36},
		{"key": "european", "value": 36},
		{"key": "found", "value": 36},
		{"key": "high", "value": 36},
		{"key": "occur", "value": 36},
		{"key": "probably", "value": 36},
		{"key": "saola", "value": 36},
		{"key": "trade", "value": 36},
		{"key": "fragmentation", "value": 35},
		{"key": "potential", "value": 35},
		{"key": "significant", "value": 35},
		{"key": "increase", "value": 34},
		{"key": "national", "value": 34},
		{"key": "recent", "value": 34},
		{"key": "cause", "value": 33},
		{"key": "disease", "value": 33},
		{"key": "introduced", "value": 33},
		{"key": "long", "value": 33},
		{"key": "part", "value": 33},
		{"key": "since", "value": 33},
		{"key": "extinction", "value": 32},
		{"key": "feral", "value": 32},
		{"key": "include", "value": 32},
		{"key": "low", "value": 32},
		{"key": "one", "value": 32},
		{"key": "risk", "value": 32},
		{"key": "can", "value": 31},
		{"key": "development", "value": 31},
		{"key": "seal", "value": 31},
		{"key": "even", "value": 30},
		{"key": "illegal", "value": 30},
		{"key": "last", "value": 30},
		{"key": "road", "value": 30},
		{"key": "slow", "value": 30},
		{"key": "increased", "value": 29},
		{"key": "many", "value": 29},
		{"key": "restricted", "value": 29},
		{"key": "especially", "value": 28},
		{"key": "mining", "value": 28},
		{"key": "river", "value": 28},
		{"key": "site", "value": 28}],
	en : [
		{"key":"habitat","value":"982"},
		{"key":"population","value":"870"},
		{"key":"area","value":"673"},
		{"key":"hunting","value":"594"},
		{"key":"forest","value":"564"},
		{"key":"per","value":"428"},
		{"key":"losss","value":"416"},
		{"key":"range","value":"366"},
		{"key":"human","value":"308"},
		{"key":"livestock","value":"271"},
		{"key":"wild","value":"248"},
		{"key":"trade","value":"232"},
		{"key":"threatened","value":"231"},
		{"key":"local","value":"211"},
		{"key":"protected","value":"206"},
		{"key":"domestic","value":"204"},
		{"key":"decline","value":"201"},
		{"key":"competition","value":"200"},
		{"key":"number","value":"198"},
		{"key":"use","value":"189"},
		{"key":"agriculture","value":"179"},
		{"key":"year","value":"178"},
		{"key":"illegal","value":"175"},
		{"key":"logging","value":"172"},
		{"key":"land","value":"171"},
		{"key":"fragmentation","value":"168"},
		{"key":"plantation","value":"168"},
		{"key":"poaching","value":"168"},
		{"key":"animal","value":"167"},
		{"key":"increasing","value":"162"},
		{"key":"meat","value":"162"},
		{"key":"development","value":"161"},
		{"key":"increased","value":"161"},
		{"key":"high","value":"154"},
		{"key":"part","value":"153"},
		{"key":"result","value":"152"},
		{"key":"small","value":"152"},
		{"key":"level","value":"147"},
		{"key":"especially","value":"146"},
		{"key":"water","value":"143"},
		{"key":"agricultural","value":"142"},
		{"key":"within","value":"140"},
		{"key":"food","value":"139"},
		{"key":"conversion","value":"134"},
		{"key":"cat","value":"132"},
		{"key":"disease","value":"131"},
		{"key":"timmins","value":"129"},
		{"key":"park","value":"123"},
		{"key":"island","value":"122"},
		{"key":"mining","value":"122"},
		{"key":"hunted","value":"120"},
		{"key":"people","value":"120"},
		{"key":"khulan","value":"119"},
		{"key":"many","value":"117"},
		{"key":"significant","value":"117"},
		{"key":"conservation","value":"116"},
		{"key":"particularly","value":"116"},
		{"key":"national","value":"114"},
		{"key":"activities","value":"113"},
		{"key":"expansion","value":"112"},
		{"key":"extraction","value":"111"},
		{"key":"deer","value":"110"},
		{"key":"deforestation","value":"110"},
		{"key":"can","value":"108"},
		{"key":"viet","value":"108"},
		{"key":"cattle","value":"107"},
		{"key":"even","value":"107"},
		{"key":"large","value":"107"},
		{"key":"include","value":"106"},
		{"key":"isolated","value":"104"},
		{"key":"region","value":"104"},
		{"key":"road","value":"103"},
		{"key":"since","value":"103"},
		{"key":"destruction","value":"102"},
		{"key":"hemionus","value":"102"},
		{"key":"wildlife","value":"102"},
		{"key":"found","value":"101"},
		{"key":"much","value":"100"},
		{"key":"pet","value":"100"},
		{"key":"reserve","value":"99"},
		{"key":"grazing","value":"98"},
		{"key":"likely","value":"98"},
		{"key":"main","value":"97"},
		{"key":"pressure","value":"97"},
		{"key":"mongolia","value":"95"},
		{"key":"nam","value":"93"},
		{"key":"commercial","value":"91"},
		{"key":"introduced","value":"91"},
		{"key":"resource","value":"91"},
		{"key":"settlement","value":"91"},
		{"key":"well","value":"91"},
		{"key":"reported","value":"88"},
		{"key":"extinction","value":"87"},
		{"key":"remain","value":"87"},
		{"key":"market","value":"86"},
		{"key":"crop","value":"85"},
		{"key":"khur","value":"85"},
		{"key":"seal","value":"85"},
		{"key":"serious","value":"85"},
		{"key":"reduced","value":"84"}],
	ew : [
		{"key":"habitat","value":"3"},
		{"key":"losss","value":"2"},
		{"key":"population","value":"2"},
		{"key":"wild","value":"2"},
		{"key":"yang","value":"2"},
		{"key":"became","value":"1"},
		{"key":"can","value":"1"},
		{"key":"cao","value":"1"},
		{"key":"competition","value":"1"},
		{"key":"davidianus","value":"1"},
		{"key":"devillers","value":"1"},
		{"key":"devillersterschuren","value":"1"},
		{"key":"diversity","value":"1"},
		{"key":"domestic","value":"1"},
		{"key":"exist","value":"1"},
		{"key":"extinct","value":"1"},
		{"key":"extinction","value":"1"},
		{"key":"freeranging","value":"1"},
		{"key":"genetic","value":"1"},
		{"key":"hunting","value":"1"},
		{"key":"identified","value":"1"},
		{"key":"including","value":"1"},
		{"key":"increased","value":"1"},
		{"key":"kingswood","value":"1"},
		{"key":"livestock","value":"1"},
		{"key":"longterm","value":"1"},
		{"key":"low","value":"1"},
		{"key":"main","value":"1"},
		{"key":"mallon","value":"1"},
		{"key":"morrow","value":"1"},
		{"key":"much","value":"1"},
		{"key":"native","value":"1"},
		{"key":"oryx","value":"1"},
		{"key":"overhunting","value":"1"},
		{"key":"press","value":"1"},
		{"key":"reasons","value":"1"},
		{"key":"reintroduced","value":"1"},
		{"key":"remains","value":"1"},
		{"key":"reported","value":"1"},
		{"key":"scimitarhorned","value":"1"},
		{"key":"since","value":"1"},
		{"key":"size","value":"1"},
		{"key":"state","value":"1"},
		{"key":"time","value":"1"},
		{"key":"unclear","value":"1"},
		{"key":"zeng","value":"1"}],
	ex : [
		{"key":"extinction","value":"68"},
		{"key":"rat","value":"45"},
		{"key":"introduced","value":"34"},
		{"key":"island","value":"32"},
		{"key":"andrews","value":"22"},
		{"key":"rattus","value":"22"},
		{"key":"cat","value":"19"},
		{"key":"extinct","value":"19"},
		{"key":"human","value":"19"},
		{"key":"predation","value":"19"},
		{"key":"likely","value":"18"},
		{"key":"habitat","value":"16"},
		{"key":"hunting","value":"15"},
		{"key":"reason","value":"15"},
		{"key":"website","value":"15"},
		{"key":"macleari","value":"14"},
		{"key":"unknown","value":"14"},
		{"key":"aurochs","value":"12"},
		{"key":"cattle","value":"12"},
		{"key":"cause","value":"12"},
		{"key":"decline","value":"12"},
		{"key":"hippopotamid","value":"12"},
		{"key":"introduction","value":"12"},
		{"key":"sea","value":"12"},
		{"key":"black","value":"11"},
		{"key":"european","value":"11"},
		{"key":"known","value":"11"},
		{"key":"native","value":"11"},
		{"key":"animal","value":"10"},
		{"key":"competition","value":"10"},
		{"key":"food","value":"10"},
		{"key":"hunted","value":"10"},
		{"key":"last","value":"10"},
		{"key":"probably","value":"10"},
		{"key":"years","value":"10"},
		{"key":"disease","value":"9"},
		{"key":"forest","value":"9"},
		{"key":"foxes","value":"9"},
		{"key":"losss","value":"9"},
		{"key":"specimens","value":"9"},
		{"key":"thought","value":"9"},
		{"key":"contributed","value":"8"},
		{"key":"disappeared","value":"8"},
		{"key":"factor","value":"8"},
		{"key":"impact","value":"8"},
		{"key":"mongoose","value":"8"},
		{"key":"nativitatis","value":"8"},
		{"key":"norris","value":"8"},
		{"key":"pickering","value":"8"},
		{"key":"spp","value":"8"},
		{"key":"century","value":"7"},
		{"key":"collected","value":"7"},
		{"key":"feral","value":"7"},
		{"key":"lead","value":"7"},
		{"key":"madagascar","value":"7"},
		{"key":"predators","value":"7"},
		{"key":"burning","value":"6"},
		{"key":"domesticated","value":"6"},
		{"key":"durham","value":"6"},
		{"key":"fossil","value":"6"},
		{"key":"found","value":"6"},
		{"key":"ground","value":"6"},
		{"key":"hunters","value":"6"},
		{"key":"interest","value":"6"},
		{"key":"king","value":"6"},
		{"key":"main","value":"6"},
		{"key":"period","value":"6"},
		{"key":"poland","value":"6"},
		{"key":"possibly","value":"6"},
		{"key":"prior","value":"6"},
		{"key":"remains","value":"6"},
		{"key":"royal","value":"6"},
		{"key":"time","value":"6"},
		{"key":"van","value":"6"},
		{"key":"vuure","value":"6"},
		{"key":"well","value":"6"},
		{"key":"zygmunt","value":"6"},
		{"key":"became","value":"5"},
		{"key":"central","value":"5"},
		{"key":"christmas","value":"5"},
		{"key":"demise","value":"5"},
		{"key":"driven","value":"5"},
		{"key":"evidence","value":"5"},
		{"key":"fire","value":"5"},
		{"key":"late","value":"5"},
		{"key":"less","value":"5"},
		{"key":"population","value":"5"},
		{"key":"possible","value":"5"},
		{"key":"rabbits","value":"5"},
		{"key":"regime","value":"5"},
		{"key":"remained","value":"5"},
		{"key":"report","value":"5"},
		{"key":"two","value":"5"},
		{"key":"unable","value":"5"},
		{"key":"used","value":"5"},
		{"key":"areas","value":"4"},
		{"key":"began","value":"4"},
		{"key":"centuries","value":"4"},
		{"key":"combination","value":"4"},
		{"key":"considered","value":"4"}],
	vu: [
		{"key":"habitat","value":"1089"},
		{"key":"area","value":"932"},
		{"key":"population","value":"791"},
		{"key":"hunting","value":"757"},
		{"key":"per","value":"674"},
		{"key":"forest","value":"624"},
		{"key":"losss","value":"583"},
		{"key":"range","value":"370"},
		{"key":"gaur","value":"357"},
		{"key":"protected","value":"303"},
		{"key":"logging","value":"246"},
		{"key":"human","value":"244"},
		{"key":"threatened","value":"243"},
		{"key":"animal","value":"237"},
		{"key":"decline","value":"229"},
		{"key":"meat","value":"228"},
		{"key":"local","value":"225"},
		{"key":"park","value":"207"},
		{"key":"hunted","value":"202"},
		{"key":"conversion","value":"200"},
		{"key":"part","value":"199"},
		{"key":"reserve","value":"188"},
		{"key":"trade","value":"187"},
		{"key":"domestic","value":"185"},
		{"key":"agriculture","value":"180"},
		{"key":"food","value":"180"},
		{"key":"large","value":"175"},
		{"key":"national","value":"175"},
		{"key":"india","value":"171"},
		{"key":"high","value":"170"},
		{"key":"livestock","value":"167"},
		{"key":"conservation","value":"163"},
		{"key":"year","value":"163"},
		{"key":"number","value":"159"},
		{"key":"within","value":"158"},
		{"key":"agricultural","value":"156"},
		{"key":"likely","value":"154"},
		{"key":"poaching","value":"154"},
		{"key":"well","value":"154"},
		{"key":"much","value":"153"},
		{"key":"use","value":"152"},
		{"key":"used","value":"149"},
		{"key":"even","value":"145"},
		{"key":"many","value":"144"},
		{"key":"island","value":"143"},
		{"key":"plantation","value":"143"},
		{"key":"pet","value":"142"},
		{"key":"deforestation","value":"141"},
		{"key":"particularly","value":"140"},
		{"key":"land","value":"138"},
		{"key":"fragmentation","value":"137"},
		{"key":"change","value":"127"},
		{"key":"illegal","value":"124"},
		{"key":"probably","value":"124"},
		{"key":"factor","value":"123"},
		{"key":"including","value":"122"},
		{"key":"densities","value":"121"},
		{"key":"least","value":"118"},
		{"key":"commercial","value":"117"},
		{"key":"degradation","value":"116"},
		{"key":"effect","value":"116"},
		{"key":"reduced","value":"116"},
		{"key":"bear","value":"115"},
		{"key":"occur","value":"115"},
		{"key":"wildlife","value":"115"},
		{"key":"still","value":"113"},
		{"key":"include","value":"112"},
		{"key":"level","value":"112"},
		{"key":"small","value":"111"},
		{"key":"development","value":"109"},
		{"key":"fire","value":"109"},
		{"key":"relatively","value":"106"},
		{"key":"road","value":"102"},
		{"key":"sambar","value":"102"},
		{"key":"throughout","value":"100"},
		{"key":"china","value":"99"},
		{"key":"competition","value":"99"},
		{"key":"impact","value":"99"},
		{"key":"found","value":"98"},
		{"key":"increase","value":"98"},
		{"key":"region","value":"97"},
		{"key":"serious","value":"95"},
		{"key":"deer","value":"94"},
		{"key":"disturbance","value":"94"},
		{"key":"nam","value":"94"},
		{"key":"especially","value":"93"},
		{"key":"known","value":"93"},
		{"key":"wild","value":"93"},
		{"key":"malaysia","value":"92"},
		{"key":"mortality","value":"91"},
		{"key":"southeast","value":"90"},
		{"key":"two","value":"90"},
		{"key":"disease","value":"89"},
		{"key":"hedges","value":"88"},
		{"key":"increased","value":"88"},
		{"key":"main","value":"88"},
		{"key":"protection","value":"88"},
		{"key":"asia","value":"87"},
		{"key":"management","value":"87"},
		{"key":"destruction","value":"86"}]
}


